# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dr. Benjamin Kirtman Research Group
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the website dedicated to Dr. Benjamin Kirtman and his research group. Here you can find information on the research him and his group take part in, as well as learn more about Dr. Kirtman and his collegues and students. 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <style>
        .container {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh; /* Adjust the height as needed */
            padding: 20px;
        }
        .photo {
            flex: 1;
            max-width: 50%;
        }
        .photo img {
            width: 100%;
            height: auto;
        }
        .text {
            flex: 1;
            max-width: 50%;
            padding-left: 20px; /* Adjust the spacing between text and photo */
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="photo">
            <img src="/kirtman_pic.jpg"
        </div>
        <div class="text">
            <h1>Welcome to My Website</h1>
            <p>This is a brief introduction or description that you want to show beside your photo. You can customize this text to fit your needs.</p>
            <!-- Add more text or elements as needed -->
        </div>
    </div>
</body>
</html>




# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
